import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const artifacts = [
  ["darkPoolDexAbi", "artifacts/contracts/DarkPoolDex.sol/DarkPoolDex.json"],
  ["mockTokenAbi", "artifacts/contracts/MockToken.sol/MockToken.json"],
] as const;

async function main() {
  const generatedDir = path.join(process.cwd(), "src", "generated");
  await mkdir(generatedDir, { recursive: true });

  const lines = [
    "/* Autogenerated by scripts/export-abi.ts. */",
    "import type { Abi } from 'viem';",
    "",
  ];

  for (const [name, artifactPath] of artifacts) {
    const artifact = JSON.parse(await readFile(path.join(process.cwd(), artifactPath), "utf8"));
    lines.push(`export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const satisfies Abi;`);
    lines.push("");
  }

  await writeFile(path.join(generatedDir, "abis.ts"), `${lines.join("\n")}\n`);
  console.log("Wrote src/generated/abis.ts");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
